name: Release obsidian plugin

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events to matching any tag format, i.e. 1.0, 20.15.10

env:
  PLUGIN_NAME: obsidian-dynamic-toc # Change this to the name of your plugin-id folder

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x" # You might need to adjust this value to your own version
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Build
        run: |
          pnpm install
          pnpm build
          mkdir ${{ env.PLUGIN_NAME }}
          cp dist/main.js dist/manifest.json dist/styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.PLUGIN_NAME }}.zip
            dist/main.js
            dist/styles.css
            dist/manifest.json
